### ISSUE TITLE
Update to 0.14.3

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#17]
this issue is a prerequisite for updating the amber-website to version 0.14.3

**Comment by herby** [comment]
Since amber-attic is already taken care of, 0.14.1->0.14.2 is not an issue (trysmalltalk is a library more or less and selecting whether to include es5-shim and ie8 compat should be on app), and 0.14.2->0.14.3 does not need any migration, I would propose to close this. `trysmalltalk` already is in 0.14.3 (just do `bower install`).

**Comment by hhzl** [comment]
Not fixed in the master branch.

**Comment by hhzl** [comment]
fixed with #28
